version: '3'

services:
  grafana:
    hostname: grafana
    image: grafana/grafana:latest
    networks:
      - internal
      - external
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro

  timescaledb:
    hostname: postgres
    image: timescale/timescaledb:1.4.2-pg10
    networks:
      internal:
        aliases:
          - postgres
    expose:
      - 5432
    ports:
      - 55435:5432

  tsrelay:
    hostname: tsrelay
    image: runejuhl/netdata-tsrelay:1571856892
    command: 'netdata_tsrelay --dbopts="host=postgres port=5432 dbname=metrics user=user1 password=password" --listen-addr 0.0.0.0 --debug'
    networks:
      internal:
        aliases:
          - tsrelay
      external:
        aliases:
          - tsrelay

  netdata:
    image: firehol/netdata:latest
    networks:
      - external
      - internal
    ports:
      - 19999:19999
    volumes:
      - ./netdata.conf:/etc/netdata/netdata.conf

networks:
  external:
  internal:
